//274
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.1.2.274")]
[assembly: AssemblyVersion("1.1.2.99")]
[assembly: KSPAssembly("MoarKerbals", 1,1,2)]

namespace MoarKerbals
{
	public static class Version
	{
		public const int major = 1;
		public const int minor = 1;
		public const int patch = 2;
		public const int build = 99;
		public const string Number = "1.1.2.99";
#if DEBUG
		public const string Text = Number + "-zed'K DEBUG";
#else
		public const string Text = Number + "-prerelease zed'K ";
		public const string SText = Number;
#endif
	}
}